repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: format
        name: Format maintained Python files
        language: system
        entry: make format
        pass_filenames: false
        stages: [pre-commit]