[project]
name = "lunio"
version = "0.1.0"
description = "A Lunio coding challenge Python project managed with Poetry."
authors = [
    { name = "Thomas Weisner" }
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "openpyxl>=3.1.5,<4.0.0",
    "pandas>=2.3.3,<3.0.0",
]

[tool.poetry]
packages = [
    { include = "lunio", from = "src" }
]

[tool.poetry.group.dev.dependencies]
nox = "^2025.5.1"
nox-poetry = "^1.2.0"
pre-commit = "^4.2.0"
pytest = "^8.4.1"
ruff = "^0.12.2"
ipykernel = "^7.3.0"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[tool.ruff]
line-length = 88
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
